# Generated by Django 5.1.4 on 2025-01-14 21:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('secid', models.CharField(max_length=10)),
                ('custom_secname', models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)])),
                ('quantity', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('date', models.DateField()),
                ('use_custom', models.BooleanField(default=False)),
                ('st', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='stocks.stocks')),
            ],
        ),
    ]
