# Generated by Django 5.1.4 on 2025-01-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDealInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('secid', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('buy_price', models.IntegerField()),
                ('date', models.DateField()),
                ('stocks', models.ManyToManyField(to='stocks.stockinfosecurities')),
            ],
        ),
        migrations.DeleteModel(
            name='UserTradeInfo',
        ),
    ]
