# Generated by Django 5.1.4 on 2025-01-16 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0002_alter_userdealinfo_st'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdealinfo',
            name='secid',
        ),
        migrations.RemoveField(
            model_name='userdealinfo',
            name='st',
        ),
        migrations.RemoveField(
            model_name='userdealinfo',
            name='username',
        ),
        migrations.AddField(
            model_name='userdealinfo',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stocks'),
        ),
        migrations.AddField(
            model_name='userdealinfo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
