# Generated by Django 5.1.4 on 2025-01-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userdealinfo_delete_usertradeinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdealinfo',
            old_name='stocks',
            new_name='stock',
        ),
    ]
