# Generated by Django 5.1.4 on 2025-01-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0003_rename_stocks_userdealinfo_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdealinfo',
            name='stock',
        ),
        migrations.AddField(
            model_name='userdealinfo',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockinfosecurities'),
        ),
    ]
