# Generated by Django 5.1.4 on 2025-01-16 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
        ('users', '0003_remove_userdealinfo_secid_remove_userdealinfo_st_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDealInfo',
            new_name='DealInfo',
        ),
    ]
