# Generated by Django 5.1.4 on 2025-01-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_userdealinfo_stock_userdealinfo_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdealinfo',
            name='custom_secname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
