# Generated by Django 5.1.4 on 2025-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_userdealinfo_dealinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealinfo',
            name='lower_border',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='dealinfo',
            name='upper_border',
            field=models.FloatField(default=None, null=True),
        ),
    ]
