# Generated by Django 5.1.4 on 2025-01-14 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdealinfo_custom_secname'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdealinfo',
            name='use_custom',
            field=models.BooleanField(default=False),
        ),
    ]
