# Generated by Django 5.1.4 on 2025-01-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notificationuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationuser',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
