# Generated by Django 5.1.4 on 2025-01-17 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_notificationuser_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationUser',
        ),
    ]
