# Generated by Django 5.1.5 on 2025-01-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_delete_notificationuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealinfo',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
