# Generated by Django 5.1.6 on 2025-03-09 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealinfo',
            name='buy_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
