# Generated by Django 5.1.6 on 2025-03-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dealinfo',
            old_name='custom_secname',
            new_name='custom_name',
        ),
    ]
