# Generated by Django 5.1.6 on 2025-03-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
