# Generated by Django 5.1.6 on 2025-02-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationuser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 8, 46, 40, 6366, tzinfo=datetime.timezone.utc)),
        ),
    ]
