# Generated by Django 5.1.6 on 2025-02-18 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notificationuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 10, 49, 41, 938621, tzinfo=datetime.timezone.utc)),
        ),
    ]
