# Generated by Django 5.1.6 on 2025-02-18 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationuser_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationuser',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
