# Generated by Django 4.2.4 on 2024-05-13 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='my_gallery/django')),
            ],
        ),
        migrations.CreateModel(
            name='DjangoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('chapter_name', models.CharField(max_length=30)),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DjangoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
