# Generated by Django 4.2.4 on 2024-05-13 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='djangoinfo',
            name='files',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_app.djangoimage'),
        ),
        migrations.AddField(
            model_name='djangoinfo',
            name='links',
            field=models.ManyToManyField(blank=True, to='django_app.djangolink'),
        ),
    ]
