# Generated by Django 4.2.4 on 2024-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0003_alter_djangolink_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoinfo',
            name='chapter_name',
            field=models.CharField(max_length=40),
        ),
    ]
