# Generated by Django 4.2.4 on 2024-05-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0004_alter_djangoinfo_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoinfo',
            name='chapter_name',
            field=models.CharField(max_length=50),
        ),
    ]
