# Generated by Django 4.2.4 on 2024-05-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0006_alter_djangoinfo_chapter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoinfo',
            name='number',
            field=models.IntegerField(unique=True),
        ),
    ]
