# Generated by Django 5.1.6 on 2025-02-17 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_cronlogs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocks',
            name='prevdate',
        ),
        migrations.RemoveField(
            model_name='stocks',
            name='settledate',
        ),
        migrations.AlterField(
            model_name='cronlogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 5, 25, 21, 544390, tzinfo=datetime.timezone.utc)),
        ),
    ]
