# Generated by Django 5.1.6 on 2025-02-17 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_remove_stocks_prevdate_remove_stocks_settledate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 17, 8, 46, 40, 4947, tzinfo=datetime.timezone.utc)),
        ),
    ]
