# Generated by Django 5.1.6 on 2025-02-18 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_cronlogs_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronlogs',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 10, 49, 41, 936558, tzinfo=datetime.timezone.utc)),
        ),
    ]
