# Generated by Django 5.1.4 on 2025-01-01 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secid', models.CharField(max_length=40)),
                ('boardid', models.CharField(max_length=40)),
                ('shortname', models.CharField(max_length=40)),
                ('lotsize', models.IntegerField()),
                ('secname', models.CharField(max_length=40)),
                ('listlevel', models.IntegerField()),
                ('issuesize', models.IntegerField()),
            ],
        ),
    ]
