# Generated by Django 5.1.4 on 2025-01-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='issuesize',
            field=models.PositiveBigIntegerField(),
        ),
    ]
