# Generated by Django 5.1.4 on 2025-01-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='boardname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='currencyid',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='decimals',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='faceunit',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='facevalue',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='instrid',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='isin',
            field=models.CharField(default='', max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='latname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='marketcode',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='minstep',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevdate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevlegalcloseprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevwaprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='regnumber',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='remarks',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='sectorid',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='sectype',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='settledate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='status',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='boardid',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='issuesize',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='listlevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lotsize',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='secid',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='secname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shortname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
