# Generated by Django 5.1.4 on 2025-01-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfo',
            name='boardname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='facevalue',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='high',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='isin',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='latname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='low',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='open',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevdate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevlegalcloseprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='prevwaprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='settledate',
            field=models.DateField(default='1111-11-11'),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='valtoday',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='valtoday_usd',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='value',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='value_usd',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='stockinfo',
            name='waprice',
            field=models.FloatField(default=0.1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='boardid',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='issuesize',
            field=models.PositiveBigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='listlevel',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lotsize',
            field=models.IntegerField(default=0.1),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='secid',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='secname',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shortname',
            field=models.CharField(default='', max_length=40),
        ),
    ]
