# Generated by Django 5.1.4 on 2025-01-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stockinfo_boardid_alter_stockinfo_boardname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='secid',
            field=models.CharField(max_length=10),
        ),
    ]
