# Generated by Django 5.1.4 on 2025-01-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stockinfo_id_alter_stockinfo_isin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='open',
            field=models.FloatField(null=True),
        ),
    ]
