# Generated by Django 5.1.5 on 2025-02-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stocks_prevprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='prevwaprice',
            field=models.FloatField(null=True),
        ),
    ]
