# Generated by Django 5.1.5 on 2025-02-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_stocks_prevwaprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocks',
            name='prevlegalcloseprice',
            field=models.FloatField(null=True),
        ),
    ]
