# Generated by Django 5.1.4 on 2025-01-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stockinfo_high_alter_stockinfo_low_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfo',
            name='boardid',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='boardname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='facevalue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='high',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='isin',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='issuesize',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='latname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='listlevel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='lotsize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='low',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prevdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prevlegalcloseprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prevprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='prevwaprice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='secname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='settledate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='shortname',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='valtoday',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='valtoday_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='value_usd',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='stockinfo',
            name='waprice',
            field=models.FloatField(null=True),
        ),
    ]
