# Generated by Django 5.1.4 on 2025-01-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_stockinfo_last'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfoMarketdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secid', models.CharField(max_length=10, unique=True)),
                ('open', models.FloatField(null=True)),
                ('low', models.FloatField(null=True)),
                ('high', models.FloatField(null=True)),
                ('last', models.FloatField(null=True)),
                ('value', models.FloatField(null=True)),
                ('value_usd', models.FloatField(null=True)),
                ('waprice', models.FloatField(null=True)),
                ('valtoday', models.FloatField(null=True)),
                ('valtoday_usd', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockInfoSecurities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secid', models.CharField(max_length=10, unique=True)),
                ('boardid', models.CharField(max_length=40)),
                ('shortname', models.CharField(max_length=40)),
                ('prevprice', models.FloatField()),
                ('lotsize', models.IntegerField()),
                ('facevalue', models.FloatField()),
                ('boardname', models.CharField(max_length=40)),
                ('secname', models.CharField(max_length=40)),
                ('prevwaprice', models.FloatField()),
                ('prevdate', models.DateField()),
                ('issuesize', models.PositiveBigIntegerField()),
                ('isin', models.CharField(max_length=40)),
                ('latname', models.CharField(max_length=40)),
                ('prevlegalcloseprice', models.FloatField()),
                ('listlevel', models.IntegerField()),
                ('settledate', models.DateField()),
            ],
        ),
    ]
