# Generated by Django 5.1.4 on 2025-01-07 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stockinfomarketdata_stockinfosecurities'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfosecurities',
            name='marketdata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stockinfomarketdata'),
        ),
    ]
