# Generated by Django 5.1.4 on 2025-01-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stockinfosecurities_marketdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfomarketdata',
            name='secid',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='stockinfosecurities',
            name='secid',
            field=models.CharField(max_length=10),
        ),
    ]
