# Generated by Django 5.1.4 on 2025-01-07 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_stockinfomarketdata_secid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockInfo',
        ),
    ]
