# Generated by Django 5.1.4 on 2025-01-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_delete_stockinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfosecurities',
            name='changeable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stockinfosecurities',
            name='marketdata',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.stockinfomarketdata'),
        ),
    ]
