# Generated by Django 5.1.4 on 2025-01-07 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stockinfosecurities_changeable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockinfosecurities',
            old_name='changeable',
            new_name='unchangeable',
        ),
    ]
