# Generated by Django 5.1.4 on 2025-01-07 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_alter_stockinfosecurities_shortname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfosecurities',
            name='secname',
            field=models.CharField(max_length=40, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='stockinfosecurities',
            name='shortname',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
