# Generated by Django 5.1.4 on 2025-01-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_alter_stockinfosecurities_secname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinfomarketdata',
            name='secid',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stockinfosecurities',
            name='secid',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
