# Generated by Django 5.1.4 on 2025-01-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_alter_stockinfomarketdata_secid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockinfomarketdata',
            name='boardid',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
